// Styles extracted from the UI prototype
// Matches the design pixel-for-pixel

export const S = {
  page: { minHeight: "100vh", background: "#f0f0f0", display: "flex", justifyContent: "center", alignItems: "flex-start", padding: "28px 16px", fontFamily: "'IBM Plex Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif" },
  card: { background: "#fff", borderRadius: 8, overflow: "hidden", maxWidth: 620, width: "100%", boxShadow: "0 1px 4px rgba(0,0,0,0.07)" },
  wide: { background: "#fff", borderRadius: 8, overflow: "hidden", maxWidth: 760, width: "100%", boxShadow: "0 1px 4px rgba(0,0,0,0.07)" },
  bar: { height: 5, background: "#2774AE" },
  body: { padding: "36px 36px 32px" },
  code: { fontSize: 12, fontWeight: 700, color: "#2774AE", letterSpacing: "0.08em", textTransform: "uppercase", margin: 0 },
  h1: { fontSize: 24, fontWeight: 700, color: "#1a1a1a", margin: "5px 0 3px", lineHeight: 1.2 },
  sub: { fontSize: 13.5, color: "#666", margin: 0 },
  h2: { fontSize: 17, fontWeight: 600, color: "#1a1a1a", margin: "0 0 14px" },
  meta: { fontSize: 13, color: "#888", margin: "8px 0 14px", fontWeight: 500 },
  hr: { height: 1, background: "#e4e4e4", margin: "20px 0" },
  box: { background: "#fafafa", border: "1px solid #e8e8e8", borderRadius: 6, padding: "14px 18px", marginBottom: 16 },
  boxLabel: { fontSize: 11, fontWeight: 700, color: "#888", textTransform: "uppercase", letterSpacing: "0.06em", margin: "0 0 8px" },
  boxItem: { fontSize: 13.5, color: "#333", margin: "5px 0", lineHeight: 1.5 },
  boxNum: { fontWeight: 700, color: "#2774AE", marginRight: 4 },
  label: { display: "block", fontSize: 11, fontWeight: 700, color: "#888", textTransform: "uppercase", letterSpacing: "0.06em", marginBottom: 6 },
  inp: { width: "100%", padding: "10px 12px", fontSize: 15, fontFamily: "'IBM Plex Sans', sans-serif", border: "2px solid #d0d0d0", borderRadius: 6, outline: "none", boxSizing: "border-box" },
  ans: { width: "100%", padding: "11px 13px", fontSize: 15, fontFamily: "'IBM Plex Mono', 'Menlo', monospace", border: "2px solid #d0d0d0", borderRadius: 6, outline: "none", resize: "vertical", boxSizing: "border-box", lineHeight: 1.6 },
  err: { marginTop: 8, padding: "8px 12px", borderRadius: 5, fontSize: 13, fontWeight: 600, background: "#fdf0ef", color: "#c0392b", border: "1px solid #f0c4c1" },
  ok: { marginTop: 8, padding: "8px 12px", borderRadius: 5, fontSize: 13, fontWeight: 600, background: "#eaf7f0", color: "#1e7a47", border: "1px solid #b8e6cc" },
  fb: { marginTop: 8, padding: "8px 12px", borderRadius: 5, fontSize: 13, fontWeight: 600 },
  fbP: { background: "#eaf7f0", color: "#1e7a47", border: "1px solid #b8e6cc" },
  fbF: { background: "#fdf0ef", color: "#c0392b", border: "1px solid #f0c4c1" },
  hdr: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "11px 24px", background: "#2774AE", color: "#fff", fontSize: 13, fontWeight: 600 },
  hdrL: { letterSpacing: "0.04em" },
  hdrC: { opacity: 0.85, fontSize: 12 },
  pill: { background: "rgba(255,255,255,0.2)", padding: "3px 10px", borderRadius: 4, fontSize: 12 },
  qb: { padding: "28px 24px 24px" },
  stud: { fontSize: 12, color: "#999", fontWeight: 500, margin: "0 0 4px" },
  ql: { fontSize: 12, fontWeight: 700, color: "#2774AE", textTransform: "uppercase", letterSpacing: "0.06em", margin: "0 0 10px" },
  qt: { fontSize: 15, color: "#1a1a1a", lineHeight: 1.55, margin: "0 0 10px" },
  mBox: { background: "#f7f7f7", border: "1px solid #e4e4e4", borderRadius: 6, padding: "10px 14px", marginBottom: 10, fontFamily: "'IBM Plex Mono', monospace" },
  mLine: { fontSize: 14, margin: "3px 0", color: "#1a1a1a" },
  mK: { fontWeight: 700, color: "#555" },
  hint: { fontSize: 13, color: "#666", fontStyle: "italic", margin: "6px 0" },
  fn: { fontSize: 13, color: "#555", margin: "6px 0 0", lineHeight: 1.5 },
  mono: { fontSize: 12, color: "#888", fontFamily: "'IBM Plex Mono', monospace" },
  bRow: { display: "flex", gap: 10, alignItems: "center", justifyContent: "space-between", flexWrap: "wrap", marginTop: 24 },
  rEnd: { display: "flex", justifyContent: "flex-end", marginTop: 24 },
  btn1: { padding: "10px 22px", background: "#2774AE", color: "#fff", border: "none", borderRadius: 6, fontSize: 14, fontWeight: 600, cursor: "pointer" },
  btn2: { padding: "10px 18px", background: "#fff", color: "#444", border: "1px solid #d0d0d0", borderRadius: 6, fontSize: 14, fontWeight: 500, cursor: "pointer" },
  btnG: { padding: "10px 22px", background: "#2d8659", color: "#fff", border: "none", borderRadius: 6, fontSize: 14, fontWeight: 600, cursor: "pointer" },
  btnCk: { padding: "10px 18px", background: "#f7f7f7", color: "#333", border: "1px solid #ccc", borderRadius: 6, fontSize: 13, fontWeight: 600, cursor: "pointer", fontFamily: "'IBM Plex Mono', monospace" },
  menuBtn: { background: "rgba(255,255,255,0.15)", border: "1px solid rgba(255,255,255,0.3)", borderRadius: 5, padding: "5px 7px", cursor: "pointer", display: "flex", alignItems: "center" },
  bk: { position: "fixed", top: 0, left: 0, right: 0, bottom: 0, zIndex: 99 },
  dd: { position: "absolute", top: "calc(100% + 8px)", right: 0, width: 180, background: "#fff", border: "1px solid #e0e0e0", borderRadius: 8, boxShadow: "0 8px 24px rgba(0,0,0,0.12)", zIndex: 100, padding: "8px 0", maxHeight: 380, overflowY: "auto" },
  ddT: { fontSize: 11, fontWeight: 700, color: "#888", textTransform: "uppercase", letterSpacing: "0.06em", padding: "4px 16px 8px", margin: 0, borderBottom: "1px solid #f0f0f0" },
  ddI: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "8px 16px", cursor: "pointer", borderLeft: "3px solid transparent" },
  ddA: { background: "#f0f7ff", borderLeft: "3px solid #2774AE" },
  ddQ: { fontSize: 13, fontWeight: 600, color: "#333" },
  ddSub: { display: "flex", alignItems: "center", justifyContent: "space-between", padding: "6px 16px 6px 38px", cursor: "pointer", borderLeft: "3px solid transparent" },
  ddSubQ: { fontSize: 12, fontWeight: 500, color: "#666" },
  nGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))", gap: 12, marginBottom: 8 },
  nGrp: { background: "#fafafa", border: "1px solid #e8e8e8", borderRadius: 6, padding: "12px 14px" },
  nGrpT: { fontSize: 13, fontWeight: 700, color: "#1a1a1a", margin: "0 0 8px" },
  nItm: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "6px 10px", marginBottom: 4, borderRadius: 4, cursor: "pointer", background: "#fff" },
  nQ: { fontSize: 13, fontWeight: 600, color: "#2774AE" },
  rRow: { display: "flex", alignItems: "center", gap: 12, padding: "11px 14px", background: "#fafafa", border: "1px solid #e8e8e8", borderRadius: 6, marginBottom: 6, cursor: "pointer" },
  rQ: { fontSize: 13, fontWeight: 700, color: "#2774AE", minWidth: 36 },
  rA: { flex: 1, fontSize: 14, fontFamily: "'IBM Plex Mono', monospace", fontWeight: 500, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  saveIndicator: { fontSize: 11, color: "#999", fontStyle: "italic", marginTop: 4 },
};
