#!/usr/bin/env python3
"""
Demo: Quine-McCluskey Solver

This demonstrates the algorithmic Boolean minimization solver that
finds minimal sum-of-products expressions without using LLMs.

NO API KEY NEEDED - pure algorithm
"""

from autota.solver.quine_mccluskey import QuineMcCluskySolver

print("="*70)
print("AutoTA Quine-McCluskey Solver Demo")
print("="*70)
print()

# Example 1: Simple 2-variable function
print("📌 Example 1: Simple 2-Variable Function")
print("-" * 70)
print("F(A,B) with minterms [1, 3]")
print()

solver = QuineMcCluskySolver(
    minterms=[1, 3],
    variables=["A", "B"]
)
result = solver.solve()
print(f"Minimal expression: {result}")
print()

# Example 2: 3-variable function
print("📌 Example 2: 3-Variable Function")
print("-" * 70)
print("F(A,B,C) with minterms [0, 2, 4, 6]")
print()

solver = QuineMcCluskySolver(
    minterms=[0, 2, 4, 6],
    variables=["A", "B", "C"]
)
result = solver.solve()
print(f"Minimal expression: {result}")
print()

# Example 3: 4-variable K-map problem
print("📌 Example 3: 4-Variable K-Map Problem")
print("-" * 70)
print("F(A,B,C,D) with minterms [0, 2, 5, 7]")
print()

solver = QuineMcCluskySolver(
    minterms=[0, 2, 5, 7],
    variables=["A", "B", "C", "D"]
)
details = solver.get_solution_details()

print(f"Minimal expression: {details['minimal_expression']}")
print(f"Number of prime implicants: {len(details['prime_implicants'])}")
print(f"Number of terms in solution: {details['num_terms']}")
print(f"Total literals: {details['total_literals']}")
print()

print("Prime implicants:")
for pi in details['prime_implicants']:
    print(f"  {pi['expression']:12} → covers {pi['minterms']}")
print()

# Example 4: With don't-cares
print("📌 Example 4: With Don't-Cares")
print("-" * 70)
print("F(A,B,C,D) with minterms [0, 2, 8, 10] and don't-cares [1, 3, 9, 11]")
print()

solver_no_dc = QuineMcCluskySolver(
    minterms=[0, 2, 8, 10],
    variables=["A", "B", "C", "D"]
)
result_no_dc = solver_no_dc.solve()

solver_with_dc = QuineMcCluskySolver(
    minterms=[0, 2, 8, 10],
    dont_cares=[1, 3, 9, 11],
    variables=["A", "B", "C", "D"]
)
result_with_dc = solver_with_dc.solve()

print(f"Without don't-cares: {result_no_dc}")
print(f"With don't-cares:    {result_with_dc}")
print()
print("✓ Don't-cares enabled more aggressive minimization!")
print()

# Example 5: Complex textbook example
print("📌 Example 5: Classic Textbook Example")
print("-" * 70)
print("F(A,B,C,D) with minterms [0, 2, 5, 7, 8, 10, 13, 15]")
print()

solver = QuineMcCluskySolver(
    minterms=[0, 2, 5, 7, 8, 10, 13, 15],
    variables=["A", "B", "C", "D"]
)
details = solver.get_solution_details()

print(f"Minimal expression: {details['minimal_expression']}")
print()

print("Prime implicants found:")
for pi in details['prime_implicants']:
    essential = " (ESSENTIAL)" if any(
        epi['binary'] == pi['binary'] for epi in details['essential_primes']
    ) else ""
    print(f"  {pi['expression']:12} → {pi['minterms']}{essential}")
print()

print(f"Essential primes: {len(details['essential_primes'])}")
print(f"Minimal cover uses: {details['num_terms']} terms")
print(f"Total literals: {details['total_literals']}")
print()

# Example 6: Verify the solution
print("📌 Example 6: Verify Solution with Boolean Verifier")
print("-" * 70)

from autota.verify.boolean import BooleanVerifier
from autota.models import ProblemVariant
from uuid import uuid4

minterms = [0, 2, 5, 7]
variables = ["A", "B", "C", "D"]

# Solve
solver = QuineMcCluskySolver(minterms=minterms, variables=variables)
minimal_expr = solver.solve()

print(f"Solved expression: {minimal_expr}")

# Verify
variant = ProblemVariant(
    variant_id=uuid4(),
    problem_text="Generated by solver",
    parameters={
        "minterms": minterms,
        "dont_cares": [],
        "variables": variables
    },
    solution={"expression": minimal_expr},
    answer_format="boolean_expression"
)

verifier = BooleanVerifier()
result = verifier.verify(variant)

print(f"Verification: {'✅ PASSED' if result.passed else '❌ FAILED'}")
print()

print("="*70)
print("🎯 Key Features Demonstrated:")
print("="*70)
print("  ✓ Finds minimal sum-of-products expressions")
print("  ✓ Handles 2, 3, 4, 5+ variables")
print("  ✓ Supports don't-care conditions")
print("  ✓ Identifies prime implicants")
print("  ✓ Finds essential primes")
print("  ✓ Produces verified correct solutions")
print("  ✓ Works completely offline (no API)")
print("  ✓ Deterministic algorithm (same input → same output)")
print()

print("="*70)
print("💡 Use Cases:")
print("="*70)
print("  1. Generate reference solutions for K-map problems")
print("  2. Check if student solutions are minimal")
print("  3. Template-based problem generation (no LLM needed)")
print("  4. Teaching tool for Boolean minimization")
print("  5. Verify LLM-generated solutions")
print()

print("Try it yourself:")
print("  autota solve -m '0,2,5,7' -v 'A,B,C,D'")
print("  autota solve -m '0,2,5,7' -v 'A,B,C,D' --details")
print("="*70)
