-- AutoTA Database Schema
-- SQLite migration file
-- Run: sqlite3 data/autota.db < migrations/001_initial_schema.sql

-- =============================================================
-- INSTITUTIONAL LAYER
-- Who teaches what, who is enrolled where
-- =============================================================

CREATE TABLE IF NOT EXISTS courses (
    id TEXT PRIMARY KEY,                    -- e.g. "ECE_M16"
    name TEXT NOT NULL,                     -- "Logic Design of Digital Systems"
    department TEXT NOT NULL                 -- "ECE"
);

CREATE TABLE IF NOT EXISTS course_offerings (
    id TEXT PRIMARY KEY,                    -- e.g. "ECE_M16_SP26"
    course_id TEXT NOT NULL REFERENCES courses(id),
    quarter TEXT NOT NULL,                  -- "Spring", "Fall", "Winter", "Summer"
    year INTEGER NOT NULL,                  -- 2026
    UNIQUE(course_id, quarter, year)
);

CREATE TABLE IF NOT EXISTS instructors (
    id TEXT PRIMARY KEY,                    -- e.g. "msrivastava"
    name TEXT NOT NULL,                     -- "Mani Srivastava"
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'instructor' -- "instructor", "ta"
);

CREATE TABLE IF NOT EXISTS sections (
    id TEXT PRIMARY KEY,                    -- e.g. "ECE_M16_SP26_1A"
    offering_id TEXT NOT NULL REFERENCES course_offerings(id),
    label TEXT NOT NULL,                    -- "1A", "1B"
    instructor_id TEXT REFERENCES instructors(id),
    UNIQUE(offering_id, label)
);

CREATE TABLE IF NOT EXISTS students (
    id TEXT PRIMARY KEY,                    -- UCLA UID e.g. "UID123456789"
    name TEXT NOT NULL,                     -- full name for identity verification
    email TEXT UNIQUE NOT NULL              -- UCLA email
);

CREATE TABLE IF NOT EXISTS enrollments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id TEXT NOT NULL REFERENCES students(id),
    section_id TEXT NOT NULL REFERENCES sections(id),
    enrolled_at TEXT DEFAULT (datetime('now')),
    dropped INTEGER DEFAULT 0,             -- 1 if student dropped the section
    UNIQUE(student_id, section_id)
);

CREATE INDEX IF NOT EXISTS idx_enrollments_section ON enrollments(section_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_student ON enrollments(student_id);


-- =============================================================
-- CONTENT LAYER
-- Assignments, problems, and the variant pool
-- =============================================================

CREATE TABLE IF NOT EXISTS assignments (
    id TEXT PRIMARY KEY,                    -- e.g. "hw5"
    offering_id TEXT NOT NULL REFERENCES course_offerings(id),
    title TEXT NOT NULL,                    -- "Homework 5 — Karnaugh Map Simplification"
    type TEXT NOT NULL DEFAULT 'homework',  -- "homework", "quiz", "exam"
    instructions TEXT,                      -- JSON array of instruction strings
    spec_path TEXT,                         -- path to YAML spec used for generation
    max_attempts INTEGER NOT NULL DEFAULT 1,-- homework=3, quiz=1, exam=1
    time_limit_minutes INTEGER,             -- NULL for untimed, 30 for quiz, etc.
    is_active INTEGER DEFAULT 1,
    opens_at TEXT,                          -- when students can start (NULL = immediately)
    closes_at TEXT,                         -- hard deadline (NULL = no deadline)
    created_at TEXT DEFAULT (datetime('now'))
);

CREATE INDEX IF NOT EXISTS idx_assignments_offering ON assignments(offering_id);

CREATE TABLE IF NOT EXISTS problems (
    id TEXT PRIMARY KEY,                    -- e.g. "hw5_1a"
    assignment_id TEXT NOT NULL REFERENCES assignments(id),
    parent_label TEXT NOT NULL,             -- "1", "2", "3"
    sub_label TEXT,                         -- "a", "b", "c" or NULL if standalone
    display_order INTEGER NOT NULL,         -- 1, 2, 3... for rendering sequence
    problem_type TEXT NOT NULL,             -- "kmap_simplification" — maps to verifier registry
    text TEXT NOT NULL,                     -- problem statement shown to student
    hint TEXT,                              -- optional hint text
    answer_format TEXT NOT NULL,            -- "boolean_expression", "value", "number", "truth_table"
    placeholder TEXT,                       -- input placeholder e.g. "e.g. A'B + CD'"
    points REAL NOT NULL DEFAULT 1.0,       -- weight for scoring (not all problems equal)
    -- Sub-part dependency: if this part depends on a prior part's answer,
    -- the system shows the correct answer from the parent when rendering this part.
    -- See ARCHITECTURE.md: "Self-contained multi-part problems"
    depends_on_problem_id TEXT REFERENCES problems(id),
    UNIQUE(assignment_id, display_order)
);

CREATE INDEX IF NOT EXISTS idx_problems_assignment ON problems(assignment_id);

-- The variant pool: pre-generated, pre-verified problem variants.
-- Generated by `autota generate-template` or `autota generate` (LLM).
-- Each variant is one concrete instantiation of a problem with specific
-- parameters and a known-correct solution.
--
-- COMBINATORIAL MODEL:
-- Generate ~10 variants per problem. With N problems per assignment,
-- the number of unique assignment combinations is 10^N.
-- For 6 problems: 10^6 = 1,000,000 unique assignments.
-- For 3 independent problems (sub-parts share parent variant): 10^3 = 1,000.
-- A class of 200 students × 3 attempts = 600 needed. Pool is more than sufficient.

CREATE TABLE IF NOT EXISTS variant_pool (
    id TEXT PRIMARY KEY,                    -- UUID from ProblemVariant
    problem_id TEXT NOT NULL REFERENCES problems(id),
    -- Problem parameters (what the student sees)
    parameters_json TEXT NOT NULL,          -- JSON: minterms, dont_cares, variables, etc.
    parameter_hash TEXT NOT NULL,           -- SHA256 of canonical parameters for dedup
    problem_text TEXT,                      -- variant-specific text override (NULL = use problem.text)
    minterms TEXT,                          -- display string e.g. "m(2, 5, 6, 7)"
    dont_cares TEXT,                        -- display string e.g. "d(1, 3)" or NULL
    -- Solution (NEVER sent to frontend)
    solution_json TEXT NOT NULL,            -- JSON: correct answer(s), method, explanation
    -- Metadata
    generated_by TEXT NOT NULL DEFAULT 'template', -- "template" or "llm"
    verified INTEGER NOT NULL DEFAULT 1,    -- 1 = passed Layer 3 verification
    created_at TEXT DEFAULT (datetime('now')),
    UNIQUE(problem_id, parameter_hash)     -- no duplicate variants for same problem
);

CREATE INDEX IF NOT EXISTS idx_variant_pool_problem ON variant_pool(problem_id);


-- =============================================================
-- STUDENT WORK LAYER
-- Attempts, variant assignments, drafts, submissions, attestations
-- =============================================================

-- An attempt represents one complete pass through an assignment.
-- State machine: created → in_progress → submitted → graded
-- A student can only have ONE non-submitted attempt at a time.
CREATE TABLE IF NOT EXISTS attempts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id TEXT NOT NULL REFERENCES students(id),
    assignment_id TEXT NOT NULL REFERENCES assignments(id),
    attempt_number INTEGER NOT NULL,        -- 1, 2, 3...
    status TEXT NOT NULL DEFAULT 'created',  -- "created", "in_progress", "submitted", "graded"
    started_at TEXT DEFAULT (datetime('now')),
    submitted_at TEXT,
    attestation_signed INTEGER DEFAULT 0,
    attestation_signed_at TEXT,
    UNIQUE(student_id, assignment_id, attempt_number)
);

CREATE INDEX IF NOT EXISTS idx_attempts_student ON attempts(student_id, assignment_id);

-- Which pool variant was drawn for each problem in each attempt.
-- Created when the attempt is created. Immutable after creation.
-- On retry: new attempt → new draws from pool (excluding previously seen variants).
CREATE TABLE IF NOT EXISTS variant_assignments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    attempt_id INTEGER NOT NULL REFERENCES attempts(id),
    problem_id TEXT NOT NULL REFERENCES problems(id),
    variant_id TEXT NOT NULL REFERENCES variant_pool(id),
    UNIQUE(attempt_id, problem_id)
);

CREATE INDEX IF NOT EXISTS idx_variant_assignments_attempt ON variant_assignments(attempt_id);

-- Constraint enforced in application code:
-- For sub-parts (e.g. Q1a, Q1b, Q1c), all sub-parts within the same parent
-- MUST draw from the same parent variant or coordinated variants.
-- i.e. Q1b depends on Q1a's specific minterms, so they share the variant draw.

-- Auto-saved drafts. Mutable. Updated on every debounced save (every ~3 seconds).
-- One row per problem per attempt. Upserted on save.
CREATE TABLE IF NOT EXISTS draft_answers (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    attempt_id INTEGER NOT NULL REFERENCES attempts(id),
    problem_id TEXT NOT NULL REFERENCES problems(id),
    answer_raw TEXT NOT NULL DEFAULT '',     -- exactly what the student typed
    updated_at TEXT DEFAULT (datetime('now')),
    UNIQUE(attempt_id, problem_id)
);

CREATE INDEX IF NOT EXISTS idx_drafts_attempt ON draft_answers(attempt_id);


-- =============================================================
-- GRADING LAYER
-- Submissions (immutable) and grades
-- =============================================================

-- Final submitted answers. Created on submit. Immutable.
-- One row per problem per attempt.
CREATE TABLE IF NOT EXISTS submissions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    attempt_id INTEGER NOT NULL REFERENCES attempts(id),
    problem_id TEXT NOT NULL REFERENCES problems(id),
    variant_id TEXT NOT NULL REFERENCES variant_pool(id),
    answer_raw TEXT NOT NULL,               -- exactly what the student typed
    answer_normalized TEXT,                 -- parsed/normalized form used for grading
    submitted_at TEXT DEFAULT (datetime('now')),
    UNIQUE(attempt_id, problem_id)
);

CREATE INDEX IF NOT EXISTS idx_submissions_attempt ON submissions(attempt_id);

-- Grades per submission. May be updated if grading tier escalates.
-- Tier 1: deterministic (instant). Tier 2: LLM-assisted (async). Tier 3: human review.
CREATE TABLE IF NOT EXISTS grades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    submission_id INTEGER NOT NULL REFERENCES submissions(id),
    score REAL NOT NULL,                    -- 0.0 to 1.0
    correct INTEGER NOT NULL,              -- 0 or 1 (binary correctness)
    feedback TEXT,                          -- explanation shown to student
    grading_tier TEXT NOT NULL DEFAULT 'deterministic', -- "deterministic", "llm", "human"
    grading_status TEXT NOT NULL DEFAULT 'graded', -- "graded", "pending", "needs_review"
    graded_by TEXT,                         -- NULL for deterministic, model name for LLM, instructor ID for human
    graded_at TEXT DEFAULT (datetime('now')),
    -- If re-graded (e.g. Tier 1 → Tier 3 override), store history
    previous_score REAL,
    previous_feedback TEXT,
    regraded_at TEXT,
    UNIQUE(submission_id)                   -- one grade per submission (latest wins)
);

CREATE INDEX IF NOT EXISTS idx_grades_submission ON grades(submission_id);

-- Aggregate score per attempt. Computed after all problems in an attempt are graded.
-- Stored for fast lookup (denormalized from grades + problems.points).
CREATE TABLE IF NOT EXISTS attempt_results (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    attempt_id INTEGER NOT NULL REFERENCES attempts(id),
    total_score REAL NOT NULL,              -- weighted sum: Σ(grade.score × problem.points) / Σ(problem.points)
    total_points_earned REAL NOT NULL,      -- Σ(grade.score × problem.points)
    total_points_possible REAL NOT NULL,    -- Σ(problem.points)
    problems_correct INTEGER NOT NULL,      -- count of grade.correct = 1
    problems_total INTEGER NOT NULL,        -- total problems in assignment
    computed_at TEXT DEFAULT (datetime('now')),
    UNIQUE(attempt_id)
);


-- =============================================================
-- QUIZ SESSION LAYER (Phase 5 stub — tables created now, not populated)
-- =============================================================

CREATE TABLE IF NOT EXISTS quiz_sessions (
    id TEXT PRIMARY KEY,                    -- short code e.g. "QZ-5A3F"
    assignment_id TEXT NOT NULL REFERENCES assignments(id),
    section_id TEXT REFERENCES sections(id),-- NULL = open to all sections
    created_by TEXT NOT NULL REFERENCES instructors(id),
    qr_url TEXT,                            -- URL encoded in QR code
    status TEXT NOT NULL DEFAULT 'pending',  -- "pending", "active", "closed"
    opens_at TEXT,
    closes_at TEXT,
    time_limit_minutes INTEGER,             -- overrides assignment time_limit if set
    created_at TEXT DEFAULT (datetime('now'))
);


-- =============================================================
-- VIEWS for common queries
-- =============================================================

-- Student's current attempt status for an assignment
CREATE VIEW IF NOT EXISTS v_student_attempt_status AS
SELECT
    a.student_id,
    a.assignment_id,
    a.attempt_number,
    a.status,
    a.started_at,
    a.submitted_at,
    ar.total_score,
    ar.problems_correct,
    ar.problems_total,
    asn.max_attempts,
    CASE WHEN a.attempt_number < asn.max_attempts AND a.status = 'graded' THEN 1 ELSE 0 END AS can_retry
FROM attempts a
JOIN assignments asn ON a.assignment_id = asn.id
LEFT JOIN attempt_results ar ON a.id = ar.attempt_id;

-- Full grade report: student × problem × grade for an assignment
CREATE VIEW IF NOT EXISTS v_grade_report AS
SELECT
    s.id AS student_id,
    s.name AS student_name,
    a.assignment_id,
    a.attempt_number,
    p.parent_label,
    p.sub_label,
    p.points AS problem_points,
    sub.answer_raw,
    g.score,
    g.correct,
    g.feedback,
    g.grading_tier
FROM submissions sub
JOIN attempts a ON sub.attempt_id = a.id
JOIN students s ON a.student_id = s.id
JOIN problems p ON sub.problem_id = p.id
LEFT JOIN grades g ON sub.id = g.submission_id;
